### PR TITLE
Origin/rule parser

### PR DESCRIPTION
**Pull request by A3onn**

### CODE REVIEW

**Review by Astalios — COMMENTED** [review]
is good

**Review by Astalios — COMMENTED** [review]
is good

**Review by Astalios — APPROVED** [review]

**Review by ArgenT1x — APPROVED** [review]

**Review by ArgenT1x — APPROVED** [review]

**Review by Astalios — APPROVED** [review]
c bon

**Review by Astalios — APPROVED** [review]
c good

**Pull request merged**
